name: Dot Net Framework 4 (Release)

on:
   push:
     tags:
       - '*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master
   
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore log4net.Appender.Loki.sln
    
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: Build
      run: msbuild log4net.Appender.Loki.csproj /p:Configuration=Release
   
    - name: Create NuGet Package
      run: nuget pack log4net.Appender.Loki.csproj -OutputDirectory ./artifact -Prop Configuration=Release
   
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifact
        path: ./artifact
